"""make_delivery_address_nullable

Revision ID: 674eb7ac8148
Revises: ebfecd060fe7
Create Date: 2025-10-12 18:07:01.948690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674eb7ac8148'
down_revision: Union[str, Sequence[str], None] = 'ebfecd060fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, make delivery_address nullable for cart orders
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.TEXT(),
               nullable=True)
    
    # Update restaurants with null addresses to have a default value
    op.execute("UPDATE restaurants SET address = location WHERE address IS NULL")
    
    # Now make address NOT NULL
    op.alter_column('restaurants', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
